<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Common/Results/" />
    <Folder Include="Common/Results/Abstractions/" />
    <Folder Include="Persons/Enums/" />
  </ItemGroup>
</Project>
